///////////////////////////////////////////////////////////
//  Store.cs
//  Implementation of the Class IStorable
//  Generated by Enterprise Architect
//  Created on:      11-апр-2015 10:17:56
//  Original author: User
///////////////////////////////////////////////////////////




using System.Collections.Generic;
public class IStorable {

	public IStorable(){

	}

	~IStorable(){

	}

	public virtual void Dispose(){

	}

	public bool Delete(){

		return false;
	}

	public bool Insert(){

		return false;
	}

	public IStorable Select(){

		return null;
	}

	public List<IStorable> SelectAll(){

		return null;
	}

	public bool Update(){

		return false;
	}

}//end IStorable