//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSCore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class OboznPos
    {
        [Key]
        public int idOPos { get; set; }
        public string TIP { get; set; }
        public string IND { get; set; }
        public string PICH { get; set; }
        public Nullable<int> CHZ { get; set; }
        public string PICHN { get; set; }
    }
}
