//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempPOSPRIMB
    {
        public int id_record { get; set; }
        public string TIP { get; set; }
        public string IND1 { get; set; }
        public string PICH { get; set; }
        public string IND2 { get; set; }
        public string P2NI { get; set; }
        public string Z { get; set; }
        public Nullable<int> NS { get; set; }
        public Nullable<double> KSP { get; set; }
        public Nullable<double> KSZ { get; set; }
        public int Depth { get; set; }
        public string id { get; set; }
        public int Parent { get; set; }
    }
}
