//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSCore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class ZakazVPR
    {
        [Key, Column(Order = 0)]
        public string Z { get; set; }
        public Nullable<System.DateTime> D { get; set; }
        public string PTP { get; set; }
        public string T_KU { get; set; }
        [Key, Column(Order = 1)]
        public string IND_KU { get; set; }
        [Key, Column(Order = 2)]
        public string OBOZN_KU { get; set; }
        public string T_CH { get; set; }
         [Key, Column(Order = 3)]
        public string IND_CH { get; set; }
         [Key, Column(Order = 4)]
        public string OBOZN_CH { get; set; }
        public Nullable<double> KSP { get; set; }
        public string id { get; set; }
    }
}
