///////////////////////////////////////////////////////////
//  Work.cs
//  Implementation of the Class Work
//  Generated by Enterprise Architect
//  Created on:      11-апр-2015 10:22:39
//  Model: Kotova Marina, Vinnichenko Dmitry 
//  Developer: Dergachev Constantine
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AECSCore
{
    public class Work
    {

    }
}
