///////////////////////////////////////////////////////////
//  Work.cs
//  Implementation of the Class Work
//  Generated by Enterprise Architect
//  Created on:      11-апр-2015 10:22:39
//  Model: Kotova Marina, Vinnichenko Dmitry 
//  Developer: Dergachev Constantine
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AECSCore
{
    public class Work
    {
        public Int32 Id { get; set; }

        public String Name { get; set; }

        public Work Parent { get; set; }

        public Department Department { get; set; }

        public Double Duration { get; set; }

        public Int32 ChainNumber { get; set; }

        /// <summary>
        /// May or may be not presented at the root level
        /// </summary>
        public Element Element { get; set; }

        public Double XOffset { get; set; }

        



    }
}
